.TH TEM Server
.SH NAME 
TEM Server \- Server for The Encrypted Messenger
.SH SYNOPSIS
.B tem_server [PORT]
.SH DESCRIPTION
.I TEM_Server 
is the server which 
.I TEM 
clients connect to. It includes capabilities for account creation and encryption. Generate keys and certificate with "openssl req -x509 -newkey rsa:4096 -out cert.pem -outform PEM -days 1825".
.SH "SEE ALSO"
tem(1), openssl(1)
